### ISSUE TITLE
Не фиксируются данные профиля.

### ISSUE THREAD

**Issue by jumper423** [EMALLStudio/appmetrica_sdk#1]
Версия 0.0.2+1

Подобный код
```
AppmetricaSdk().reportUserProfileCustomNumber(key: 'ID', value: this.id.toDouble());
AppmetricaSdk().reportUserProfileUserName(userName: this.name);
```
не фиксирует данные профиля в appmetrica. Т.е. у пользователей доступна только стандартная информация, тип устройства, разрешение и прочее.

Внутрь того как устроенно внутри сильно не капал, но заметил что вызов
```
await _channel
        .invokeMethod<void>('reportUserProfileUserName', <String, dynamic>{
      'userName': userName,
    });
```
возвращает null

**Comment by formatCvt** [comment]
привет, с predefined есть какая-то проблема (причем на iOS и на Android), а вот с кастомными все норм, что бы они учитывались их необходимо добавить в настроках приложения. 
![Screenshot 2019-09-25 at 5 05 56 PM](https://user-images.githubusercontent.com/9342933/65608395-d0b3d880-dfb6-11e9-95d6-c164a3545fca.png)

**Comment by formatCvt** [comment]
Как оказалось, что бы собирались predefined обязательно необходимо устанавливать еще и атрибут ProfileId. В версию 0.0.3 добавлена функция `setUserProfileID` и после установки id они начинают собираться:

![Screenshot 2019-09-29 at 3 07 00 PM](https://user-images.githubusercontent.com/9342933/65832543-df0f3680-e2cd-11e9-940f-0e55cd8a8289.png)

**Comment by jumper423** [comment]
Спасибо, помогло

**Comment by formatCvt** [comment]
пожалуйста =)
