### ISSUE TITLE
Null safety 

### ISSUE THREAD

**Issue by jumper423** [EMALLStudio/appmetrica_sdk#11]
https://dart.dev/null-safety/migration-guide

**Comment by kcrebound** [comment]
https://github.com/EMALLStudio/appmetrica_sdk/pull/10

**Comment by Bhagat8533** [comment]
https://github.com/EMALLStudio/appmetrica_sdk/pull/10#issuecomment-804812817

**Comment by formatCvt** [comment]
Thanks everyone, null safety added!
