### ISSUE TITLE
MissingPluginException(No implementation found for method activate on channel emallstudio.com/appmetrica_sdk)

### ISSUE THREAD

**Issue by RenatFakhrutdinov** [EMALLStudio/appmetrica_sdk#7]
Hi!
When i'm trying to launch app, my app crushes with error

`E/flutter ( 9208): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
E/flutter ( 9208): <asynchronous suspension>
E/flutter ( 9208): #1      AppmetricaSdk.activate (package:appmetrica_sdk/src/appmetrica_sdk.dart:56:20)
E/flutter ( 9208): #2      main (package:spintowinclone/main.dart:13:8)
E/flutter ( 9208): #3      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
E/flutter ( 9208): #4      main (package:spintowinclone/main.dart:8:10)
E/flutter ( 9208): #5      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
E/flutter ( 9208): #6      _rootRun (dart:async/zone.dart:1126:13)
E/flutter ( 9208): #7      _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter ( 9208): #8      _runZoned (dart:async/zone.dart:1518:10)
E/flutter ( 9208): #9      runZoned (dart:async/zone.dart:1502:12)
E/flutter ( 9208): #10     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
E/flutter ( 9208): #11     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
E/flutter ( 9208): #12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
E/flutter ( 9208): 
`

The error occurres when app trying to do this part of code

`await AppmetricaSdk()
      .activate(apiKey: 'db2206ed-c61a-43aa-b95c-6912f60bd25e');` //apiKey from example

**Comment by formatCvt** [comment]
@RenatFakhrutdinov Thanks for reporting. I can't reproduce this. Can you check these questions list here https://github.com/flutter/flutter/issues/10912#issuecomment-310499594

**Comment by RenatFakhrutdinov** [comment]
@formatCvt 
I don't know what happen then, but now I can't reproduce this either. Hope it will continue to work well.

**Comment by formatCvt** [comment]
you're welcome =)
