### ISSUE TITLE
Does the plugin support attributing app installs?

### ISSUE THREAD

**Issue by alectogeek** [EMALLStudio/appmetrica_sdk#8]
Does the plugin support the feature when we can link a user's ad click and his further ivents from installed app? Especially for iOS

**Comment by formatCvt** [comment]
Yes it is. For iOS you should add `iAd.framework`. Integration instructions are available here https://developer.apple.com/documentation/iad/setting_up_apple_search_ads_attribution (see paragraph Add the iAd Framework to Your Xcode Project). Before submitting your app for review, ensure your app complies with IDFA usage guidelines
For Android you should add `implementation 'com.android.installreferrer:installreferrer:1.1.2'` in the dependencies block of project `android/app/build.gradle` file (starting next release SDK developers promise do it automatically)

**Comment by alectogeek** [comment]
Hmm, I saw nothing regarding iAd.framework, so I just followed instructions from pub and sent my app to the app store. I will try and if it doesn't work will follow your instructions. Thanks!

**Comment by formatCvt** [comment]
You're welcome! 
I will update instructions within next release

**Comment by alectogeek** [comment]
So, the attribution didn't work. I'll follow your instructions. Could you, please, clarify the point about headers here: `Import iAd Headers into your app. These headers are typically in the file that contains your attribution code. The header file corresponds to the iOS version for which you compile your app in Xcode. Apple Search Ads attribution requires iOS 10.0 and later.`

**Comment by alectogeek** [comment]
Also could you, please, suggest about embedding the framework? Apple instructions that you mentioed doesn't say anything about it.

![изображение](https://user-images.githubusercontent.com/18165303/86060193-edf96400-ba6c-11ea-8a7b-b340fea48d95.png)

**Comment by formatCvt** [comment]
try with `Do Not Embed` please

**Comment by formatCvt** [comment]
instructions updated.
